const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const {RepositoryActionService, handleRepositoryRequest} = require('../src/classes/repositoryService.js');
const {RepositoryRunProfileService} = require('../src/classes/repositoryRunProfileService.js');
const {ControlPlaneService} = require('../src/classes/controlPlaneService.js');
const {RepositoryLauncher} = require('../src/classes/repositoryLauncher.class.js');
const {RepositoryRunSelectionStore} = require('../src/classes/repositoryRunSelectionStore.js');

async function main() {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'nomad-profile-selection-'));
    try {
        const id = `repo_${'a'.repeat(32)}`;
        const repository = {id, canonicalPath: root, executionIdentity: 'execution', repositoryIdentity: `sha256:${'b'.repeat(64)}`, public: {id, displayName: 'FIXTURE'}};
        const manifest = scripts => fs.writeFileSync(path.join(root, 'package.json'), JSON.stringify({scripts}));
        manifest({dev: 'node dev.js'});
        const profiles = new RepositoryRunProfileService({trustStorePath: path.join(root, 'trust.json')});
        const repositories = {repositories: new Map([[id, repository]]), refresh: async () => ({repositories: [repository.public]}), resolveRepository: async value => { assert.strictEqual(value, id); return repository; }};
        let securityProfile = 'NORMAL';
        const starts = [];
        const processManager = {isActive: () => false, getStatus: () => null, getActiveRepositorySnapshots: () => [], getExecutionSecurityStatus: () => ({allowed: securityProfile !== 'LOCKDOWN', securityProfile}), start: (r, p) => { starts.push(p); return {ok: true, status: 'RUNNING'}; }};
        const options = {repositoryService: repositories, runProfileService: profiles, processManager, gitService: {isUpdating: () => false, inspectUpdate: async () => ({ok: false})}, runSelectionPath: path.join(root, 'preferences', 'selection.json')};
        let actions = new RepositoryActionService(options);
        const ephemeralOnly = path.join(root, 'must-not-persist.json');
        const memory = new RepositoryRunSelectionStore(ephemeralOnly, () => false);
        memory.set(id, {fingerprint: `sha256:${'d'.repeat(64)}`, profileId: 'npm-dev'});
        assert(!fs.existsSync(ephemeralOnly), 'unverified PUBLIC/LOCKDOWN persistence remains session-only');
        let listed = (await actions.list()).repositories[0];
        assert.strictEqual(listed.selectedRunProfileId, 'npm-dev', 'one fixed profile auto-selects');
        assert.deepStrictEqual(listed.runProfiles, [{profileId: 'npm-dev', displayName: 'NPM DEV'}]);
        assert(!JSON.stringify(listed).includes('node dev.js'), 'renderer does not receive commands');
        manifest({dev: 'node dev.js', start: 'node start.js', arbitrary: 'never exposed'});
        listed = (await actions.list()).repositories[0];
        assert.strictEqual(listed.selectedRunProfileId, null, 'changed profile set clears selection');
        assert.deepStrictEqual(listed.runProfiles.map(p => p.profileId), ['npm-dev', 'npm-start']);
        profiles.discover(repository).forEach(p => profiles.approve(repository, p));
        assert.strictEqual((await actions.execute(id, 'run')).status, 'RUN PROFILE SELECTION REQUIRED');
        const select = profileId => handleRepositoryRequest(actions, {operation: 'select-run-profile', repositoryId: id, profileId});
        assert.strictEqual((await select('npm-arbitrary')).ok, false);
        assert.strictEqual((await select('npm-start; touch BAD')).ok, false);
        assert.strictEqual((await handleRepositoryRequest(actions, {operation: 'select-run-profile', repositoryId: id, profileId: 'npm-start', args: ['evil']})).ok, false);
        assert.strictEqual((await actions.execute(id, 'run', undefined, {profileId: 'npm-arbitrary'})).ok, false);
        assert.strictEqual(starts.length, 0);
        assert.strictEqual((await select('npm-start')).ok, true);
        assert.strictEqual((await handleRepositoryRequest(actions, {operation: 'action', repositoryId: id, actionId: 'run'})).ok, true);
        assert.strictEqual(starts.pop().profileId, 'npm-start', 'RUN uses selected profile');
        actions = new RepositoryActionService(options);
        assert.strictEqual((await actions.list()).repositories[0].selectedRunProfileId, 'npm-start', 'preference survives service restart');
        const control = new ControlPlaneService({repositoryActions: actions, profileService: {get: () => ({profile: securityProfile})}});
        control.setContext({selectedRepositoryId: id});
        assert.strictEqual((await control.interpret('corre este repo')).ok, true);
        assert.strictEqual(starts.pop().profileId, 'npm-start', 'assistant shares selected profile');
        securityProfile = 'LOCKDOWN';
        assert.strictEqual((await actions.execute(id, 'run')).ok, false);
        assert.strictEqual((await control.interpret('corre este repo')).ok, false);
        assert.strictEqual(starts.length, 0);
        securityProfile = 'NORMAL';
        manifest({dev: 'node changed.js', start: 'node start.js'});
        assert.strictEqual((await actions.execute(id, 'run')).status, 'RUN PROFILE SELECTION REQUIRED', 'run revalidates without a UI refresh');
        assert.strictEqual((await actions.list()).repositories[0].selectedRunProfileId, null);
        actions = new RepositoryActionService(options);
        assert.strictEqual((await actions.list()).repositories[0].selectedRunProfileId, null, 'invalidation persists');
        await select('npm-start');
        repository.repositoryIdentity = `sha256:${'c'.repeat(64)}`;
        assert.strictEqual((await actions.list()).repositories[0].selectedRunProfileId, null, 'repository replacement clears selection');
        manifest({});
        listed = (await actions.list()).repositories[0];
        assert.deepStrictEqual(listed.runProfiles, []);
        assert.strictEqual(listed.actions.find(a => a.id === 'run').enabled, false);

        // Exercise the actual selector renderer, without coupling tests to HTML source text.
        const element = () => ({children: [], textContent: '', appendChild(child) { this.children.push(child); }, setAttribute() {}, addEventListener(name, fn) { this[name] = fn; }});
        const launcher = new RepositoryLauncher();
        launcher.document = {createElement: element};
        launcher.profileControlElement = element();
        launcher._renderRunProfiles({runProfiles: [{profileId: 'npm-dev', displayName: 'NPM DEV'}, {profileId: 'npm-start', displayName: 'NPM START'}], selectedRunProfileId: null});
        assert.strictEqual(launcher.profileControlElement.textContent, 'RUN PROFILE ');
        assert.strictEqual(launcher.profileSelectElement.children[0].textContent, 'SELECT PROFILE');
        assert.strictEqual(launcher.profileSelectElement.children.length, 3);
        let chosen;
        launcher.selectRunProfile = value => { chosen = value; };
        launcher.profileSelectElement.value = 'npm-start';
        launcher.profileSelectElement.change();
        assert.strictEqual(chosen, 'npm-start');
        launcher._renderRunProfiles({runProfiles: [], selectedRunProfileId: null});
        assert.strictEqual(launcher.profileControlElement.textContent, 'NO RUN PROFILE');
        assert.strictEqual(launcher.profileSelectElement, null);
        console.log('Run profile selection: auto-selection, explicit selection, safe projection, RUN/assistant, persistence, invalidation, rejected IDs, selector, no-profile state and LOCKDOWN passed');
    } finally { fs.rmSync(root, {recursive: true, force: true}); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
